import {Book} from '../types/book';

export const bookList: Book[] = [
  {
    id: 0,
    name: "アンドロイドは電気羊の夢を見るか？",
    detail: "第三次大戦後の未来、サンフランシスコを舞台に賞金稼ぎのリック・デッカードが、火星から逃亡してきた8体のアンドロイドを「処理」するというあらすじ",
    evaluation: "90",
    genreList: [`ミステリー`, `ノンフィクション`],
  },
  {
    id: 1,
    name: "岩田さん: 岩田聡はこんなことを話していた。",
    detail: "任天堂の元社長、岩田聡さんのことばをまとめた本",
    evaluation: "90",
    genreList: [`コメディ`, `ファンタジー`],
  },
  {
    id: 2,
    name: "1Q84",
    detail: "村上春樹による近未来的な世界観を描いた小説。異なる時間軸が交差する物語。",
    evaluation: "85",
    genreList: [`フィクション`, `ドラマ`],
  },
  {
    id: 3,
    name: "告白",
    detail: "湊かなえによる衝撃的なミステリー小説。教師の復讐を描いた物語。",
    evaluation: "92",
    genreList: [`ミステリー`, `スリラー`],
  },
  {
    id: 4,
    name: "夜は短し歩けよ乙女",
    detail: "森見登美彦による幻想的な青春恋愛小説。",
    evaluation: "88",
    genreList: [`ロマンス`, `ファンタジー`],
  },
  {
    id: 5,
    name: "ゼロの使い魔",
    detail: "異世界の魔法学院を舞台にしたライトノベルシリーズ。",
    evaluation: "80",
    genreList: [`ファンタジー`, `アクション`],
  },
  {
    id: 6,
    name: "もし高校野球の女子マネージャーがドラッカーの『マネジメント』を読んだら",
    detail: "ドラッカーの経営学を野球部のマネジメントに応用する物語。",
    evaluation: "83",
    genreList: [`ノンフィクション`, `スポーツ`],
  },
  {
    id: 7,
    name: "海辺のカフカ",
    detail: "村上春樹の哲学的なファンタジー小説。",
    evaluation: "95",
    genreList: [`フィクション`, `ファンタジー`],
  },
  {
    id: 8,
    name: "僕のヒーローアカデミア",
    detail: "超能力を持つ社会でヒーローを目指す少年の成長物語。",
    evaluation: "89",
    genreList: [`アクション`, `少年漫画`],
  },
  {
    id: 9,
    name: "日本の歴史",
    detail: "日本の歴史をわかりやすく解説した書籍。",
    evaluation: "78",
    genreList: [`ノンフィクション`, `ドキュメンタリー`],
  },
  {
    id: 10,
    name: "三体",
    detail: "中国のSF作家・劉慈欣による壮大なスケールのSF小説。",
    evaluation: "97",
    genreList: [`SF`, `スリラー`],
  },
  {
    id: 11,
    name: "シャーロック・ホームズの冒険",
    detail: "世界的に有名な名探偵シャーロック・ホームズの短編集。",
    evaluation: "94",
    genreList: [`ミステリー`, `クラシック`],
  },
  {
    id: 12,
    name: "未来の年表",
    detail: "日本社会の未来予測に関するノンフィクション。",
    evaluation: "85",
    genreList: [`ノンフィクション`, `社会`],
  },
  {
    id: 13,
    name: "君の名は。",
    detail: "新海誠による映画のノベライズ。運命に引き寄せられる二人の青春ファンタジー。",
    evaluation: "91",
    genreList: [`ロマンス`, `ファンタジー`],
  },
  {
    id: 14,
    name: "ハリーポッターと賢者の石",
    detail: "J.K.ローリングによる大人気ファンタジーシリーズの第1作。",
    evaluation: "98",
    genreList: [`ファンタジー`, `アドベンチャー`],
  }
];
